# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Pocket Kitchen' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Pocket Kitchen
  pod 'Parse'
  pod 'AFNetworking'
  pod 'DateTools'
  pod 'EGOCache', '~> 2.2.0'
  pod 'SFProgressCircle'
  pod 'PKYStepper', '0.0.1'
  pod 'GoogleMLKit/BarcodeScanning'
  pod 'PopupKit'
  pod "SideNavigation", :git => 'https://github.com/CNKCQ/SideNavigation.git'

  target 'Pocket KitchenTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Pocket KitchenUITests' do
    # Pods for testing
  end

end
