# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'pocket kitchen' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for pocket kitchen
  pod 'Parse'
  pod 'AFNetworking'

  target 'pocket kitchenTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'pocket kitchenUITests' do
    # Pods for testing
  end

end
